# Generated by Django 3.2.9 on 2021-11-14 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member_tracing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membertracing',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='membertracing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membertracing',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membertracing',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
